import React from 'react'

const Stats = () => {
  return (
    <div className="mb-10 mt-16">
      <div className="bg-white p-8 min-h-[350px] flex flex-col items-center justify-center font-[sans-serif] text-[#333]">
        <h2 className="text-3xl font-bold mb-14 text-center">
          Smart Academy Metrics
        </h2>
        <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              5.4<span className="text-blue-600">M+</span>
            </h3>
            <p className="text-base font-bold mt-3">Total Users</p>
            <p className="text-sm text-gray-500 mt-2">
              The total number of registered users on the platform.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              $80<span className="text-blue-600">K</span>
            </h3>
            <p className="text-base font-bold mt-3">Revenue</p>
            <p className="text-sm text-gray-500 mt-2">
              The total revenue generated by the application.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              100<span className="text-blue-600">K</span>
            </h3>
            <p className="text-base font-bold mt-3">Engagement</p>
            <p className="text-sm text-gray-500 mt-2">
              The level of user engagement with the application&apos;s content
              and features.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-4xl font-extrabold">
              99.9<span className="text-blue-600">%</span>
            </h3>
            <p className="text-base font-bold mt-3">Server Uptime</p>
            <p className="text-sm text-gray-500 mt-2">
              The percentage of time the server has been operational and
              available.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Stats
