import React from 'react'

interface StatItem {
  id: number
  value: string
  valueUnit: string
  title: string
  description: string
}

const Stats: React.FC = () => {
  const statItems: StatItem[] = [
    {
      id: 1,
      value: '5.4',
      valueUnit: 'M+',
      title: 'Total Users',
      description: 'The total number of registered users on the platform.',
    },
    {
      id: 2,
      value: '$80',
      valueUnit: 'K',
      title: 'Revenue',
      description: 'The total revenue generated by the application.',
    },
    {
      id: 3,
      value: '100',
      valueUnit: 'K',
      title: 'Engagement',
      description:
        "The level of user engagement with the application's content and features.",
    },
    {
      id: 4,
      value: '99.9',
      valueUnit: '%',
      title: 'Server Uptime',
      description:
        'The percentage of time the server has been operational and available.',
    },
  ]

  return (
    <div className="mb-10 mt-16">
      <div className="bg-white p-8 min-h-[350px] flex flex-col items-center justify-center font-[sans-serif] text-[#333]">
        <h2 className="text-3xl font-bold mb-14 text-center">
          Smart Academy Metrics
        </h2>
        <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
          {statItems.map(item => (
            <div key={item.id} className="text-center">
              <h3 className="text-4xl font-extrabold">
                {item.value}
                <span className="text-blue-600">{item.valueUnit}</span>
              </h3>
              <p className="text-base font-bold mt-3">{item.title}</p>
              <p className="text-sm text-gray-500 mt-2">{item.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default Stats
